#@ load("@ytt:data", "data")

#@ def labels():
moraceae-app: "api"
#@ end

---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: xds-server
spec:
  ports:
  - port: #@ data.values.svc_port
    targetPort: #@ data.values.app_port
  selector: #@ labels()
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: xds-server
spec:
  selector:
    matchLabels: #@ labels()
  template:
    metadata:
      labels: #@ labels()
    spec:
      containers:
      - name: xds-server
        image: ko://github.com/iancoffey/moraceae/cmd/xds-server
        env:
        - name: API_MSG
          value: #@ data.values.api_msg

